### ISSUE TITLE
fatal error: unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by OrangesChen** [turner/HelloMetal#1]
When I run in my iPhone use Xcode8.0, all projects have that error, I can't find the Optional value.

**Comment by turner** [comment]
Hmmm. My setup is:

macOS Sierra Version 10.12.1
Xcode Version 8.0 (8A218a)
iOS 10.0.2

Is yours the same?

**Comment by OrangesChen** [comment]
YES, my setup are the same as yours.
![qq20161031-0](https://cloud.githubusercontent.com/assets/15519634/19841987/bea27404-9f4e-11e6-9565-95c09070278b.png)

**Comment by turner** [comment]
I did a project re-org. HelloRenderPass replaces HelloMultiPass. Give that a try. Otherwise I have no idea. The nil optional suggests you cannot allocate a device or renderpass configuration.

**Comment by OrangesChen** [comment]
Hi, I found the reason , the project first to run this method public func draw(in view: MTKView) before the method  public func mtkView(_ view: MTKView, drawableSizeWillChange size: CGSize), so the method reshape(view:view as! RenderPassMetalView) haven't go, the property "camera" hasn't value, camera.far, camera.fovYDegrees are nil.
